// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3SaeGNVWE7xpx8LQI6_gVuogo2jRrG6o',
    appId: '1:628109126126:web:02ed920ecb44f446ff86ff',
    messagingSenderId: '628109126126',
    projectId: 'transport-app-7ec0a',
    authDomain: 'transport-app-7ec0a.firebaseapp.com',
    storageBucket: 'transport-app-7ec0a.firebasestorage.app',
    measurementId: 'G-WCE4XLJ62T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGQCKF0ZuOUuCgPHwXVyfTcLelowyqnvE',
    appId: '1:628109126126:android:3d9ad8b38ffc2b12ff86ff',
    messagingSenderId: '628109126126',
    projectId: 'transport-app-7ec0a',
    storageBucket: 'transport-app-7ec0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAhNMJDzIggS7myh4mLhYbaLxgiU_Iqtw',
    appId: '1:628109126126:ios:e289805b339c3b85ff86ff',
    messagingSenderId: '628109126126',
    projectId: 'transport-app-7ec0a',
    storageBucket: 'transport-app-7ec0a.firebasestorage.app',
    iosBundleId: 'com.example.transportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAhNMJDzIggS7myh4mLhYbaLxgiU_Iqtw',
    appId: '1:628109126126:ios:e289805b339c3b85ff86ff',
    messagingSenderId: '628109126126',
    projectId: 'transport-app-7ec0a',
    storageBucket: 'transport-app-7ec0a.firebasestorage.app',
    iosBundleId: 'com.example.transportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3SaeGNVWE7xpx8LQI6_gVuogo2jRrG6o',
    appId: '1:628109126126:web:a090d663ad9f8a75ff86ff',
    messagingSenderId: '628109126126',
    projectId: 'transport-app-7ec0a',
    authDomain: 'transport-app-7ec0a.firebaseapp.com',
    storageBucket: 'transport-app-7ec0a.firebasestorage.app',
    measurementId: 'G-7EWT93BJ7H',
  );

}